(nuke|incomplete|approved)
(plz|h3ll|kiddies|siteop|0mbit|xdcc|torrent|newsgroup|emule|deluser|privmsg|l0l|h0h0|nazi)
(lalala|thetruth|ownz|appelsap|peekaboo|xs4all|pl0it|0nly|dbbot|w00t|flybye|nforce|pl1z|faggot|echoin)
(bigbird|bloemkool|ucnick|mouseman|jamil|MLG)
(?:http|w{3}|irc)\..+\.(?:com|net|org|uk|(?:inf|n)o|[in]l|[ds]e|f[ir])
^(covers|svcd|vcd|xvid|divx|apps|filled|pyro|fury|req([._-]|uest)|stolen|week.?[0-9])
^(thanks|tc|hi+|join)[._-]
#ownage etc
[0op][-().0_op]*w[-()._w]*n[-()._n]*(?:[3e][-().3_e]*d|[4a]+[-().4_a]*g[-()._g]*[3e])
#efnet
[e3][-()_.e3]*f[-()_.f]*n[-()_.n]*[e3][-()_.e3]*[7t]
#linknet
[1l][-()_.1l]*[1i][-()_.1i]*n[-()_.n]*k[-()_.k]*n[-()_.n]*[e3][-()_.e3]*[7t]
#prespam/chan/bot/test
p[-()._p]*r[-()._r]*[3e](?:(?:[-().3_e]*b[-()._b]*[0o][-().0_o]*|.*[7t][-().7_t]*[3e][-().3_e]*[5s][-().5_s]*)[7t]|[-().3_e]*(?:[5s][-().5_s]*p[-()._p]*[4a][-().4_a]*m|c[-()._c]*h[-()._h]*[4a][-().4_a]*n))
#addpre
[a4][-()_.a4]*d[-()_.d]*p[-()_.p]*r[-()_.r]*[e3]
#omfg
[0o][-()_.0o]*m[-()_.m]*f[-()_.f]*g
#stfu
[5s][-()_.5s]*[-()_.7t]*[7t]f[-()_.f]*u(?!$)
#rofl
(^|[._-])r[-()_.r]*[0o][-()_.0o]*f[-()_.f]*[1l]
r[-()_.r]*[0o][-()_.0o]*f[-()_.f]*[1l]([._-]|$)
#lmao
#[1l][-()_.1l]*m[-()_.m]*[a4][-()_.a4]*[0o]
#autoer
[a4][-()_.a4]*u[-()_.u]*[7t][-()_.7t]*[0o][-()_.0o]*[e3][-()_.e3]*r
#echoer
[e3][-()_.e3]*c[-()_.c]*h[-()_.h]*[0o][-()_.0o]*[e3][-()_.e3]*r
#h4te
h[-()_.]*[4]+[-()_.]*[7t][-()_.]*[e3]
#israel
[1i][-()_.1i]*[5s][-()_.5s]*r[-()_.r]*[a4][-()_.a4]*[e3][-()_.e3]*[1l]
#fuckyo
f[-()_.f]*u[-()_.u]*c[-()_.c]*k[-()_.k]*y[-()_.y]*[0o]
#suck*cock
[5s][-()_.5s]*u[-()_.u]*c[-()_.c]*k.+c[-()_.c]*[0o][-()_.0o]*c[-()_.c]*k
merry.+mas
happy.+year
#starting with 6 digits
^[0-9]{6,}[^._-]
#fuckoff
f[-()_.f]*u[-()_.u]*c[-()_.c]*k[-()_.k]*[0o][-()_.0o]*f[-()_.f]*f
#announce
[a4][-()_.a4]*n[-()_.n]*[0o][-()_.0o]*u[-()_.u]*n[-()_.n]*c[-()_.c]*[e3]
#fake
f[-()_.f]*[a4][-()_.a4]*k[-()_.k]*[e3]
n[-()_.n]*[0o][-()_.0o]*[0o][-()_.0o]*b
\.r[0-9]{2,}$
r[-()_.r]*[0o][-()_.0o]*x[-()_.x]*[0o][-()_.0o]*r
f1+x
f[1i]+x.*(?:(?:b[0o]+|s+h+[1i]+)t|p(?:l(?:ea)?[sz]|r[3e]))
(^|[._-])p[-()_.p]*[1l][-()_.1l]*[5s]([._-]|$)
(^|[._-])p[-()_.p]*r[-()_.r]*[e3]([._-]|$)
([._-])[5s][-()_.5s]*[u][-()_.u]*x([._-])
d[-()_.]*[0o][-()_.]*n.+[5s][-()_.]*p[-()_.]*r[-()_.]*[e3][-()_.]*[a4][-()_.]*d
(^|[._-])(ban|ddos(ing)?|releases?|j[e3]+ws?|cr[a4]+p(p+y)?)([._-]|$)
(^|[._-])(liko|gh?[4ae]+y(?:ne)?[sz]?)([._-]|$)
sh[1]+t
[7t][-()_.7t]*[e3][-()_.e3]*[5s][-()_.5s]*[7t]$
(^|[._-])truth.+-ind$
(^|[._-])last[._-]one([._-]|$)
happy.+easter
[0-9]+m[._-]*[0-9]+f
[0-9]+f[._-]*[0-9]+m
sell.+leech
[._-]kn(o|0)wn[._-]+(4|a)s
(busted|h(a|4)cked).*site
^(.+)[-._]+()\1$
cd[0-9]$
do.*not.*race
\.$
unknown$
d[-()_.d]*[0o][-()_.0o]*n[-()_.n]*[7t].*[7t][-()_.7t]*r[-()_.r]*[a4][-()_.a4]*d[-()_.d]*[e3]
d[-()_.d]*[0o][-()_.0o]*n[-()_.n]*[7t].*[r][-()_.r]*[a4][-()_.a4]*c[-()_.c]*[e3]
p\.r\.e
[5s][-()_.5s]*h[-()_.h]*u[-()_.u]*[7t].*u[-()_.u]*p
fag(s)?$
#jew stuff
j\.e\.w
^j[-()_.j]*[e3][-()_.e3]*w
j[-()._j]*[3e][-().3_e]*w(?:[-()._w]*[1i][-().1_i]*[5s][-().5_s]*h|.*(?:m[-()._m]*[0o][-().0_o]*|f[-()._f]*[4a][-().4_a]*)[7t][-().7_t]*h[-()._h]*[3e][-().3_e]*r)
h+e+h+e+
h+a+h+a+
#join chan
j[-()_.j]*[0o][-()_.0o]*[1i][-()_.1i]*n.*c[-()_.c]*h[-()_.h]*[a4][-()_.a4]*n
esexx$
#leaktest
[1l][-()_.1l]*[e3][-()_.e3]*[a4][-()_.a4]*k.*[7t][-()_.7t]*[e3][-()_.e3]*[5s][-()_.5s]*[7t]
is.*this.*true
^[0-9()._-]+$
#homo(sexual)
(^|[._-])h[-()_.h]*[0o][-()_.0o]*m[-()_.m]*[0o]([5s][-()_.5s]*[e3][-()_.e3]*x[-()_.x]*u[-()_.u]*[a4][-()_.a4]*[1l])?([._-]|$)
thn?(x|ks)
(^|[._-])ff+s([._-]|$)
c[-()_.c]*[0o][-()_.0o]*c[-()_.c]*k[-()_.k]*[1l][-()_.1l]*[0o][-()_.0o]*v[-()_.v]*[e3][-()_.e3]*r
gree+t(s|z)
auto.*trader
scene.*(h[a4]+ck|b[a4]+n)
^.{1,12}$
site.*bust
#(.{3,})\1{2}
l+a+l+a+
[-()_.]f.?x.?p[-()_.]
f.?x.?p.*(board|kid)
(the|teh).?scene
auto.*trade
[._-]10$
^[^(]+\)
-[^-]{22,}$
[a-z]0+[a-z].*-
a+f+f+i+l+s*([-()_.]|$)
busted_users$
noise-boys-....-nmc
after-all
as+hole
floffi
pre$
toejuice
-any[^-]*$
#(.{1,2})\1{3}
-(please|idiot|wmv|ass(hole)?|[0-9]cd)$
adhoc
^dupe
^(ntsc|pal)[._-]dvd.?r[._-]
-MiniDVD$
^0.?day
-(vulture|perfume)$
^latest[._]
XXXXXXX
^7b
[a-z]was$
# TEMP
88.*.22*.28
# ----
cybin
dupewhor
prewhore
sample$
sfmsubs$
-standby$
spammi
vcd.*fov$
bpm.*bpm.*bpm
#^[0-9]{2}-
justmp3$
no.reason.giv
fake.*pre
13{2,}7
cock.*fag
prehq
-switch$
pee+pee
chivas
faaa+g
do.*not.*trade
-([a-z0-9_.]+)-\1$
-guy$
kekeke
^happy.birthday
(small|big|tiny|huge).*[._-]penis
^[0-9]{4}-[0-9]{1,2}
([a-z]+[1345780][a-z]+.*){2}.*-[^-]+$
\(.\).*\(.\)
missing.*(file|nfo|sampl|scan)
^wtf
-sex$
(-[0-9]+){3}$
p2p
-private$
^the.truth
[a-z0-9]{30}
^R3Q
#DVDRIP.*DVDRIP
#2006.*2006
#HDTV.*XVID.*DVDR
#COMICS.*DVDRIP
#VA.*DVDR
#VA.*XXX
#VA.*SAT
#PS2.*XVID
#XVID.*DVDR
#S00E00
#DVDRIP.*PICXXX
#DVDRIP.*VINYL
#XVID.*XVID
#PDTV.*PALMOS
#DVDRIP.*PDTV
#XXX.*MDVDR
#VA.*HDTV
#DVDRIP.*TRAINER
#XVID.*WINALL
#EVERYBODY.HATES.DYNZ
#PAL.*NTSC
(^|[-\._])p[-\._]?r[-\._]?[e3][-\._]?[7t][-\._]?[e3][-\._]?[s5][-\._]?[t7][-\._]
(^|[-\._])[7t][-\._]?[e3][-\._]?[s5][-\._]?[t7][-\._]?p[-\._]?r[-\._]?[e3][-\._]
d[-\._]?[o0][-\._]?n[-\._]?[o0]?[-\._]?[t7].*[t7][-\._]?r[-\._]?[a4][-\._]?d[-\._]?[e3][-\._]
[-\._]?[e3][-\._]?f[-\._]?n[-\._]?[e3][-\._]?[t7]([-\._]|$)
(^|[-\._])d[-\._]?d[-\._]?[o0][-\._]?[s5][-\._].*[-_\.]?[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[-\._]?
\.(rar|r[0-9]{2}|avi|mpg|mpeg|zip|sfv|nfo|mp3|m3u|diz)$
